const soldiers = [
  { id: 'S-001', name: 'Arjun Rao', location: 'Zone A', lat: 18.525, lng: 73.855, temperature: '36.8 &deg;C', heart: '78 BPM', spo2: '98%', gas: 'Normal', battery: '87%', risk: 'Low', status: 'Active', motion: 'Stable', gps: 'Connected', lora: 'Connected', mqtt: 'Connected' },
  { id: 'S-002', name: 'Meera Singh', location: 'Zone B', lat: 18.535, lng: 73.875, temperature: '37.1 &deg;C', heart: '82 BPM', spo2: '97%', gas: 'Normal', battery: '72%', risk: 'Low', status: 'Active', motion: 'Detected', gps: 'Connected', lora: 'Connected', mqtt: 'Connected' },
  { id: 'S-003', name: 'Kabir Khan', location: 'Zone C', lat: 18.51, lng: 73.84, temperature: '39.2 &deg;C', heart: '92 BPM', spo2: '96%', gas: 'High', battery: '64%', risk: 'High', status: 'Warning', motion: 'Detected', gps: 'Connected', lora: 'Connected', mqtt: 'Connected' },
  { id: 'S-004', name: 'Nisha Menon', location: 'Zone A', lat: 18.545, lng: 73.845, temperature: '36.7 &deg;C', heart: '76 BPM', spo2: '99%', gas: 'Normal', battery: '91%', risk: 'Low', status: 'Active', motion: 'Stable', gps: 'Connected', lora: 'Connected', mqtt: 'Connected' },
  { id: 'S-005', name: 'Dev Patel', location: 'Zone D', lat: 18.515, lng: 73.89, temperature: '37.0 &deg;C', heart: '80 BPM', spo2: '98%', gas: 'Normal', battery: '83%', risk: 'Low', status: 'Active', motion: 'Stable', gps: 'Connected', lora: 'Connected', mqtt: 'Connected' },
  { id: 'S-006', name: 'Ishaan Das', location: 'Zone B', lat: 18.55, lng: 73.865, temperature: '36.9 &deg;C', heart: '79 BPM', spo2: '98%', gas: 'Normal', battery: '76%', risk: 'Low', status: 'Active', motion: 'Stable', gps: 'Connected', lora: 'Connected', mqtt: 'Connected' },
  { id: 'S-007', name: 'Tara Joseph', location: 'Zone C', lat: 18.502, lng: 73.87, temperature: '38.1 &deg;C', heart: '89 BPM', spo2: '95%', gas: 'High', battery: '59%', risk: 'Critical', status: 'Warning', motion: 'Detected', gps: 'Connected', lora: 'Connected', mqtt: 'Connected' }
];

const gasDatabase = [
  { name: 'Carbon Monoxide', severity: 'Critical', description: 'Toxic gas exposure', action: 'Immediate protective action', status: 'Monitoring' },
  { name: 'Methane', severity: 'Critical', description: 'Potentially hazardous gas', action: 'Immediate protective action', status: 'Monitoring' },
  { name: 'LPG', severity: 'Critical', description: 'Flammable gas', action: 'Move away from source', status: 'Monitoring' },
  { name: 'Smoke', severity: 'High', description: 'Possible fire or combustion', action: 'Investigate immediately', status: 'Monitoring' },
  { name: 'Unknown Gas', severity: 'Unknown', description: 'Gas detected but not identified', action: 'Treat as potentially hazardous', status: 'Monitoring' }
];

const alerts = [
  { id: 'A021', soldier: 'S-003', type: 'Higher Temperature', date: '13-09-2026', time: '09:41:12', severity: 'Warning', location: 'Zone C', description: 'Body temperature is above the normal operating range.', action: 'Soldier should check condition and move to a safer environment if required.', note: 'Body temperature crossed the configured 38.5 &deg;C threshold.', soldierNotification: 'Sent', commandNotification: 'Sent', status: 'Active' },
  { id: 'A020', soldier: 'S-007', type: 'Hazardous Gas Detected', date: '13-09-2026', time: '09:38:21', severity: 'Critical', location: 'Zone C', gas: 'Carbon Monoxide', description: 'Potentially hazardous gas detected by the MQ-2 demonstration feed.', action: 'Immediate protective action required.', note: 'Gas detection requires immediate protective action.', soldierNotification: 'Sent', commandNotification: 'Sent', status: 'Active' },
  { id: 'A019', soldier: 'S-002', type: 'Motion / Unusual Movement', date: '13-09-2026', time: '09:31:20', severity: 'High', location: 'Zone B', description: 'Unusual movement was detected by the IMU.', action: 'Soldier should verify movement and report if unexpected.', note: 'Unexpected movement detected and cleared after verification.', soldierNotification: 'Sent', commandNotification: 'Sent', status: 'Resolved' },
  { id: 'A018', soldier: 'S-004', type: 'Geofence Breach', date: '13-09-2026', time: '09:27:51', severity: 'High', location: 'Zone A', description: 'Soldier moved outside the configured boundary.', action: 'Confirm location and return to the assigned zone.', note: 'Soldier returned inside the configured Zone A boundary.', soldierNotification: 'Sent', commandNotification: 'Sent', status: 'Resolved' }
];

const app = document.getElementById('app');
const pageNames = { dashboard: 'Dashboard', soldiers: 'Soldier Details', live: 'Live Monitoring', sensors: 'Sensor Data', alerts: 'Alerts', gas: 'Hazardous Gas Database', network: 'Network Status', reports: 'Reports' };
let currentView = 'dashboard';
let chartInstances = [];
let mapInstance;

function statusClass(value) {
  const normalized = value.toLowerCase();
  if (normalized.includes('critical')) return 'red';
  if (normalized.includes('high')) return 'orange';
  if (normalized.includes('warning')) return 'amber';
  if (normalized.includes('unknown')) return 'gray';
  if (normalized.includes('offline')) return 'gray';
  return 'green';
}
function badge(value) { return `<span class="badge ${statusClass(value)}">${value}</span>`; }
function notificationBadges(alert) { return `<span class="notification-line"><span>Soldier Device</span>${badge(alert.soldierNotification || 'Sent')}<span>Command Centre</span>${badge(alert.commandNotification || 'Sent')}</span>`; }
function pageHead(eyebrow, title, subtitle, meta = '') { return `<div class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1 class="page-title">${title}</h1><p class="page-subtitle">${subtitle}</p></div>${meta ? `<div class="head-meta">${meta}</div>` : ''}</div>`; }
function sectionHeading(title, note = '') { return `<div class="section-heading"><h2>${title}</h2>${note ? `<p>${note}</p>` : ''}</div>`; }

function renderDashboard() {
  const alertRows = [...alerts].sort((a, b) => severityRank(b.severity) - severityRank(a.severity)).slice(0, 3).map(alert => `<div class="alert-row"><div class="alert-info"><strong>${alert.type}</strong><span>${alert.soldier} &middot; ${alert.time} &middot; ${alert.location}</span><small>${alert.soldierNotification === 'Sent' ? 'Soldier + Command Centre' : 'Command Centre'}</small></div>${badge(alert.severity)}</div>`).join('');
  const rows = soldiers.slice(0, 4).map(soldier => `<tr><td class="id-cell">${soldier.id}</td><td>${soldier.location}</td><td>${soldier.temperature}</td><td>${soldier.heart}</td><td>${soldier.spo2}</td><td>${badge(soldier.gas)}</td><td>${soldier.battery}</td><td>${badge(soldier.risk)}</td><td>${badge(soldier.status)}</td></tr>`).join('');
  const criticalCount = alerts.filter(alert => alert.severity === 'Critical').length;
  app.innerHTML = `${pageHead('Command center / overview', 'TACTICAL IoMT', 'Soldier Monitoring System', '<strong><span></span>System status: ONLINE</strong>Last updated <span id="pageTime"></span>')}
    <div class="stats-grid alert-summary-grid"><button class="card stat-card severity-card normal-card" data-alert-filter="Normal"><span class="stat-label">Normal</span><strong class="stat-value">08</strong><small class="stat-foot">routine conditions</small></button><button class="card stat-card severity-card warning-card" data-alert-filter="Warning"><span class="stat-label">Warning</span><strong class="stat-value">03</strong><small class="stat-foot">soldier can respond</small></button><button class="card stat-card severity-card high-card" data-alert-filter="High"><span class="stat-label">High</span><strong class="stat-value">02</strong><small class="stat-foot">requires attention</small></button><button class="card stat-card severity-card critical-card" data-alert-filter="Critical"><span class="stat-label">Critical Alerts</span><strong class="stat-value">${String(criticalCount).padStart(2, '0')}</strong><small class="stat-foot">immediate intervention</small></button><div class="card stat-card"><span class="stat-label">Online Nodes</span><strong class="stat-value">18 / 20</strong><small class="stat-foot">sensor nodes online</small></div><div class="card stat-card"><span class="stat-label">Average Battery</span><strong class="stat-value">82%</strong><small class="stat-foot">wearable nodes</small></div></div>
    <div class="section-heading"><h2>Live Soldier Status</h2><p>Simulated telemetry &middot; refresh interval 10 sec</p></div>
    <div class="card table-card"><div class="table-scroll"><table class="data-table"><thead><tr><th>Soldier ID</th><th>Location</th><th>Temperature</th><th>Heart Rate</th><th>SpO2</th><th>Gas Level</th><th>Battery</th><th>Risk Level</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div></div>
    <div class="recent-grid"><section class="card panel"><div class="section-heading"><h2>Live Alerts</h2><button class="btn small" data-view-action="alerts">View alert center</button></div><div class="alert-list">${alertRows}</div></section><section class="card panel notification-panel"><div class="section-heading"><h2>Two-way notifications</h2><p>Critical alert routing</p></div><div class="notification-flow"><div><strong>Sensor Detection</strong><small>Severity classification</small></div><div class="flow-branch"><span></span><div><strong>Soldier Device</strong><small>${badge('Sent')} Immediate alert</small></div><div><strong>Command Centre</strong><small>${badge('Sent')} Critical alert</small></div></div></div></section></div>`;
  setTimeText();
}

function severityRank(value) { return { Normal: 1, Warning: 2, High: 3, Critical: 4 }[value] || 0; }

function renderSoldiers() {
  app.innerHTML = `${pageHead('Personnel / roster', 'Soldier Details', 'Review wearable telemetry and communication state for each registered soldier.', '<strong><span></span>12 soldiers active</strong>Demo roster data')}
    <div class="toolbar"><div class="section-heading"><h2>Registered Soldiers</h2><p>Click a soldier to inspect live details</p></div><input class="search-input" id="soldierSearch" type="search" placeholder="Search ID or name..."></div>
    <div class="card table-card"><div class="table-scroll"><table class="data-table"><thead><tr><th>Soldier ID</th><th>Name</th><th>Location</th><th>Battery</th><th>GPS Status</th><th>Risk Level</th><th>Current Status</th><th>Action</th></tr></thead><tbody id="soldierRows">${soldierDetailRows(soldiers)}</tbody></table></div></div><div id="soldierDetailMount"></div>`;
  document.getElementById('soldierSearch').addEventListener('input', event => { const q = event.target.value.toLowerCase(); document.getElementById('soldierRows').innerHTML = soldierDetailRows(soldiers.filter(s => `${s.id} ${s.name} ${s.location}`.toLowerCase().includes(q))); });
}
function soldierDetailRows(items) { return items.map(s => `<tr><td class="id-cell">${s.id}</td><td>${s.name}</td><td>${s.location}</td><td>${s.battery}</td><td>${badge(s.gps)}</td><td>${badge(s.risk)}</td><td>${badge(s.status)}</td><td><button class="btn small" data-soldier="${s.id}">View Details</button></td></tr>`).join('') || '<tr><td colspan="8" class="muted-cell">No soldiers match this search.</td></tr>'; }
function showSoldier(id) {
  const s = soldiers.find(item => item.id === id); const mount = document.getElementById('soldierDetailMount');
  mount.innerHTML = `<div class="detail-layout" style="margin-top:20px"><section class="card detail-card"><div class="detail-banner"><div><p class="eyebrow">Selected personnel</p><h2>SOLDIER ${s.id}</h2><p>${s.name} &middot; ${s.location}</p></div>${badge(s.status)}</div><div class="detail-grid">${[['Location', s.location], ['GPS', s.gps], ['Temperature', s.temperature], ['Heart Rate', s.heart], ['SpO2', s.spo2], ['Motion', s.motion], ['Gas Level', s.gas], ['Battery', s.battery], ['LoRa', s.lora], ['MQTT', s.mqtt], ['Risk Level', s.risk], ['Current Status', s.status]].map(item => `<div class="detail-item"><label>${item[0]}</label><strong>${item[1].includes('Connected') ? badge(item[1]) : item[1]}</strong></div>`).join('')}</div><div class="channel-status"><h3>Alert Channel Status</h3><div><span>Soldier Device</span>${badge('Connected')}</div><div><span>Command Centre</span>${badge('Connected')}</div><div><span>Last Alert</span><strong>09:38:21</strong></div><div><span>Last Notification</span>${badge('Delivered')}</div></div></section><section class="card chart-card"><div class="section-heading"><h2>Recent readings</h2><p>Last 30 minutes &middot; simulated</p></div><div class="chart-wrap"><canvas id="soldierChart"></canvas></div></section></div>`;
  createChart('soldierChart', { type: 'line', data: { labels: ['09:16', '09:21', '09:26', '09:31', '09:36', '09:41'], datasets: [{ label: 'Temperature (C)', data: [37.1, 37.4, 37.8, 38.2, 38.8, 39.2], borderColor: '#c54a4a', backgroundColor: 'rgba(197,74,74,.08)', fill: true, tension: .35, pointRadius: 3 }] }, options: chartOptions('Temperature (C)') });
}

function renderLive() {
  app.innerHTML = `${pageHead('Operations / geospatial', 'Live Monitoring', 'Track simulated soldier positions and the latest field telemetry.', '<strong><span></span>Live feed connected</strong>Last updated <span id="pageTime"></span>')}
    <div class="map-layout"><section class="card map-card"><div id="liveMap" class="map"></div><p class="map-note">Simulated coordinates for demonstration only. Map tiles are provided by OpenStreetMap.</p></section><section class="card map-list"><div class="section-heading"><h2>Live Monitoring</h2><p>4 selected units</p></div><div class="live-list">${soldiers.slice(0, 4).map(s => `<div class="live-person"><div><strong>${s.id} <span class="muted-cell">&middot; ${s.location}</span></strong><div class="live-metrics"><span>Temp <b>${s.temperature}</b></span><span>Motion <b>${s.motion}</b></span><span>Gas <b>${s.gas}</b></span><span>Battery <b>${s.battery}</b></span></div></div>${badge(s.status)}</div>`).join('')}</div></section></div>`;
  setTimeText();
  setTimeout(initMap, 0);
}
function initMap() {
  if (!window.L) return; mapInstance = L.map('liveMap').setView([18.528, 73.86], 13); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; OpenStreetMap contributors' }).addTo(mapInstance);
  soldiers.slice(0, 4).forEach(s => { const color = statusClass(s.status); const icon = L.divIcon({ className: '', html: `<div class="map-pin ${color}"><span>${s.id.slice(-1)}</span></div>`, iconSize: [23, 23], iconAnchor: [11, 22] }); L.marker([s.lat, s.lng], { icon }).addTo(mapInstance).bindPopup(`<strong>${s.id}</strong><br>${s.location} &middot; ${s.status}`); });
}

function renderSensors() {
  const cards = [['MLX90614', 'Body temperature', '37.2 &deg;C', 'Normal'], ['MAX30102', 'Heart rate & SpO2', '82 BPM', 'Normal'], ['MPU6050', 'Motion / IMU data', 'Stable', 'Normal'], ['MQ-2', 'Gas detection', 'Normal', 'Safe'], ['NEO-6M', 'GPS location', 'Connected', 'Zone A']];
  app.innerHTML = `${pageHead('Telemetry / sensors', 'Sensor Data', 'Current readings from the wearable sensor node fleet.', '<strong><span></span>18 / 20 nodes online</strong>Values are simulated')}
    <div class="sensor-grid">${cards.map(c => `<section class="card sensor-card"><div class="sensor-code">${c[0]}</div><div class="sensor-purpose">${c[1]}</div><strong class="sensor-reading">${c[2]}</strong><div class="sensor-state">${badge(c[3])}</div></section>`).join('')}</div>
    <div class="charts-grid"><section class="card chart-panel"><div class="section-heading"><h2>Temperature</h2><p>Over time</p></div><div class="chart-wrap"><canvas id="temperatureChart"></canvas></div></section><section class="card chart-panel"><div class="section-heading"><h2>Heart Rate</h2><p>Over time</p></div><div class="chart-wrap"><canvas id="heartChart"></canvas></div></section><section class="card chart-panel"><div class="section-heading"><h2>Battery Level</h2><p>Over time</p></div><div class="chart-wrap"><canvas id="batteryChart"></canvas></div></section></div>`;
  createChart('temperatureChart', lineConfig('Temperature (C)', [36.9, 37.1, 37.0, 37.4, 37.2, 37.2], '#1e5e87'));
  createChart('heartChart', lineConfig('Heart rate (BPM)', [76, 79, 81, 80, 83, 82], '#25815f'));
  createChart('batteryChart', lineConfig('Battery (%)', [87, 86, 85, 84, 83, 82], '#bd761c'));
}
function lineConfig(label, data, color) { return { type: 'line', data: { labels: ['09:20', '09:25', '09:30', '09:35', '09:40', '09:45'], datasets: [{ label, data, borderColor: color, backgroundColor: `${color}16`, fill: true, tension: .35, pointRadius: 2 }] }, options: chartOptions(label) }; }
function chartOptions(label) { return { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false }, tooltip: { displayColors: false } }, scales: { x: { grid: { display: false }, ticks: { color: '#86939d', font: { size: 9 } } }, y: { title: { display: true, text: label, color: '#86939d', font: { size: 9 } }, grid: { color: '#edf0f2' }, ticks: { color: '#86939d', font: { size: 9 } } } } }; }
function createChart(id, config) { if (!window.Chart) return; const canvas = document.getElementById(id); if (canvas) chartInstances.push(new Chart(canvas, config)); }

function renderAlerts() {
  app.innerHTML = `${pageHead('Operations / incident log', 'Alert Center', 'Review sensor and location events from the simulated command feed.', '<strong><span></span>2 active alerts</strong>13 Sep 2026')}
    <div class="toolbar alert-toolbar"><div class="button-group" id="alertFilters"><button class="filter-button active" data-filter="All">All</button><button class="filter-button" data-filter="Normal">Normal</button><button class="filter-button" data-filter="Warning">Warning</button><button class="filter-button" data-filter="High">High</button><button class="filter-button" data-filter="Critical">Critical</button><button class="filter-button" data-filter="Active">Active</button><button class="filter-button" data-filter="Resolved">Resolved</button></div><div class="alert-searches"><input class="search-input" id="alertSoldierSearch" type="search" placeholder="Search soldier ID..."><input class="search-input" id="alertTypeSearch" type="search" placeholder="Search alert type..."></div></div>
    <div class="card table-card"><div class="table-scroll"><table class="data-table"><thead><tr><th>Alert ID</th><th>Soldier</th><th>Alert Type</th><th>Location</th><th>Time</th><th>Severity</th><th>Status</th><th>Notifications</th><th>Action</th></tr></thead><tbody id="alertRows">${alertTableRows(alerts)}</tbody></table></div></div>`;
  let activeFilter = 'All';
  const updateAlertRows = () => { const soldierQuery = document.getElementById('alertSoldierSearch').value.toLowerCase(); const typeQuery = document.getElementById('alertTypeSearch').value.toLowerCase(); const filtered = alerts.filter(alert => (activeFilter === 'All' || alert.status === activeFilter || alert.severity === activeFilter) && alert.soldier.toLowerCase().includes(soldierQuery) && alert.type.toLowerCase().includes(typeQuery)); document.getElementById('alertRows').innerHTML = alertTableRows(filtered); };
  document.querySelectorAll('#alertFilters [data-filter]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('#alertFilters [data-filter]').forEach(b => b.classList.remove('active')); button.classList.add('active'); activeFilter = button.dataset.filter; updateAlertRows(); }));
  document.getElementById('alertSoldierSearch').addEventListener('input', updateAlertRows); document.getElementById('alertTypeSearch').addEventListener('input', updateAlertRows);
}
function alertTableRows(items) { return items.map(a => `<tr><td class="id-cell">${a.id}</td><td>${a.soldier}</td><td>${a.type}</td><td class="muted-cell">${a.location}</td><td class="muted-cell">${a.time}</td><td>${badge(a.severity)}</td><td>${badge(a.status)}</td><td>${notificationBadges(a)}</td><td><button class="btn small" data-alert="${a.id}">View</button></td></tr>`).join('') || '<tr><td colspan="9" class="muted-cell">No alerts match this filter.</td></tr>'; }
function showAlert(id) { const a = alerts.find(item => item.id === id); const critical = a.severity === 'Critical'; openModal(`<p class="modal-eyebrow">${critical ? 'Critical alert' : 'Alert details'} / ${a.id}</p><h2>${a.type}</h2><p class="modal-sub">${a.date} at ${a.time}</p><div class="modal-details">${[['Alert ID', a.id], ['Soldier', a.soldier], ['Severity', badge(a.severity)], ['Location', a.location], ['Description', a.description], ['Recommended Action', a.action], ['Soldier Notification', badge(a.soldierNotification)], ['Command Centre Notification', badge(a.commandNotification)], ['Status', badge(a.status)]].map(item => `<div class="detail-item"><label>${item[0]}</label><strong>${item[1]}</strong></div>`).join('')}</div><div class="modal-footer"><button class="btn" id="modalCloseInner">Close</button><button class="btn">Acknowledge Alert</button><button class="btn primary">Mark as Resolved</button></div>`); document.getElementById('modalCloseInner').addEventListener('click', closeModal); }

function renderGasDatabase() {
  app.innerHTML = `${pageHead('Operations / gas evaluation', 'Hazardous Gas Database', 'Match demonstration gas conditions to severity and recommended action.', '<strong><span></span>MQ-2 monitoring active</strong>Demonstration mode')}
    <div class="gas-demo card panel"><div><p class="eyebrow">Gas detection test</p><h2>Simulate a detected gas</h2><p class="muted-cell">The database classifies the demonstration value and creates a two-way alert when required.</p></div><div class="gas-controls"><select id="gasSelect"><option>Carbon Monoxide</option><option>Methane</option><option>LPG</option><option>Smoke</option><option>Unknown Gas</option></select><button class="btn primary" id="evaluateGas">Evaluate Detection</button></div><div id="gasResult" class="gas-result hidden"></div></div>
    <div class="toolbar"><div class="section-heading"><h2>Hazardous Gas Records</h2><p>Search the demonstration classification list</p></div><div><input class="search-input" id="gasSearch" type="search" placeholder="Search gas name..."><button class="btn" id="addGas">Add Hazardous Gas</button></div></div>
    <div class="card table-card"><div class="table-scroll"><table class="data-table"><thead><tr><th>Gas Name</th><th>Severity</th><th>Description</th><th>Recommended Action</th><th>Status</th></tr></thead><tbody id="gasRows">${gasTableRows(gasDatabase)}</tbody></table></div></div>
    <div class="accuracy-note">Gas identification shown in demonstration mode. Actual MQ-2 sensor readings indicate gas/smoke presence and do not by themselves provide definitive gas-species identification.</div>`;
  document.getElementById('gasSearch').addEventListener('input', event => { const q = event.target.value.toLowerCase(); document.getElementById('gasRows').innerHTML = gasTableRows(gasDatabase.filter(gas => gas.name.toLowerCase().includes(q))); });
  document.getElementById('evaluateGas').addEventListener('click', () => evaluateGas(document.getElementById('gasSelect').value)); document.getElementById('addGas').addEventListener('click', showGasForm);
}
function gasTableRows(items) { return items.map(gas => `<tr><td class="id-cell">${gas.name}</td><td>${badge(gas.severity)}</td><td>${gas.description}</td><td>${gas.action}</td><td>${badge(gas.status)}</td></tr>`).join('') || '<tr><td colspan="5" class="muted-cell">No gas records match this search.</td></tr>'; }
function evaluateGas(name) { const gas = gasDatabase.find(item => item.name === name); const result = document.getElementById('gasResult'); const isUnknown = !gas || gas.severity === 'Unknown'; const severity = gas ? gas.severity : 'Warning'; const generatedId = `A${String(22 + alerts.length).padStart(3, '0')}`; alerts.unshift({ id: generatedId, soldier: 'S-003', type: isUnknown ? 'Unknown Gas Detected' : 'Hazardous Gas Detected', date: '13-09-2026', time: '10:24:18', severity, location: 'Zone C', gas: gas ? gas.name : 'Unknown Gas', description: isUnknown ? 'Gas detected but not identified by the demonstration classifier.' : `${gas.name} matched in the demonstration database.`, action: gas ? gas.action : 'Treat as potentially hazardous and review immediately.', note: 'Generated by the gas detection demonstration.', soldierNotification: 'Sent', commandNotification: 'Sent', status: 'Active' }); result.className = `gas-result ${severity.toLowerCase()}`; result.innerHTML = `<div><p class="eyebrow">${isUnknown ? 'Unknown gas detected' : severity === 'Critical' ? 'Critical alert' : `${severity} alert`}</p><h2>${severity === 'Critical' ? 'CRITICAL ALERT' : gas ? gas.name.toUpperCase() : 'UNKNOWN GAS DETECTED'}</h2><p><strong>Gas:</strong> ${gas ? gas.name : 'Unknown Gas'}</p><p><strong>Severity:</strong> ${isUnknown ? 'UNKNOWN / POTENTIALLY HAZARDOUS' : badge(severity)}</p><p><strong>Recommended Action:</strong> ${gas ? gas.action : 'Treat as potentially hazardous and review immediately.'}</p><div class="notification-grid"><div>Soldier Device ${badge('Sent')}</div><div>Command Centre ${badge('Sent')}</div></div></div><button class="btn small" data-view-action="alerts">Open Alert Center</button>`; }
function showGasForm() { openModal(`<p class="modal-eyebrow">Gas database</p><h2>Add Hazardous Gas</h2><p class="modal-sub">Add a local demonstration classification for review.</p><form id="gasForm" class="gas-form"><label>Gas Name<input required name="name"></label><label>Severity<select name="severity"><option>Normal</option><option>Warning</option><option>High</option><option>Critical</option><option>Unknown</option></select></label><label>Description<textarea required name="description"></textarea></label><label>Recommended Action<textarea required name="action"></textarea></label><div class="modal-footer"><button type="button" class="btn" id="modalCloseInner">Cancel</button><button class="btn primary">Add Record</button></div></form>`); document.getElementById('modalCloseInner').addEventListener('click', closeModal); document.getElementById('gasForm').addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.target); gasDatabase.push({ name: form.get('name'), severity: form.get('severity'), description: form.get('description'), action: form.get('action'), status: 'Monitoring' }); closeModal(); renderGasDatabase(); }); }

function renderNetwork() {
  app.innerHTML = `${pageHead('Infrastructure / communications', 'Network Status', 'Monitor the communication path from wearable nodes to the command center.', '<strong><span></span>All core services operational</strong>Architecture overview')}
    <div class="network-grid"><div class="network-metrics">${[['LoRa Communication', 'Connected', 'green'], ['MQTT Communication', 'Connected', 'green'], ['Sensor Nodes', '18 / 20 Online', 'green'], ['Data Transmission', 'Active', 'green'], ['Average Latency', '~200 ms', 'green'], ['Communication', 'Long Range', 'green'], ['Power Usage', 'Efficient', 'green'], ['Encryption', 'AES-128', 'green']].map(m => `<section class="card network-metric"><label>${m[0]}</label><strong>${m[1]}</strong><div>${badge(m[1].includes('Online') ? 'Online' : 'Operational')}</div></section>`).join('')}</div><section class="card network-diagram"><div class="section-heading"><h2>Communication Architecture</h2><p>End-to-end data path</p></div><div class="diagram-node">Wearable Sensor Node<small>Sensor acquisition</small></div><div class="diagram-connector"><span>LoRa</span></div><div class="diagram-node">Edge Device / ESP32<small>Local processing</small></div><div class="diagram-connector"><span>MQTT</span></div><div class="diagram-node">Command Center<small>Monitoring and alerts</small></div></section></div>`;
}

function renderReports() {
  app.innerHTML = `${pageHead('Analysis / export', 'Reports', 'A concise performance view based on the current simulated dataset.', '<strong><span></span>Ready to generate</strong>Report date: 13 Sep 2026')}
    <div class="toolbar"><div class="section-heading"><h2>System Performance</h2><p>Supported project observations and demo telemetry</p></div><button class="btn primary" id="generateReport">Generate Report</button></div><div class="report-grid"><section class="card report-stat"><label>Packet Delivery Ratio</label><strong>Reliable</strong><small>Qualitative project observation</small></section><section class="card report-stat"><label>Average Latency</label><strong>~200 ms</strong><small>Reported project value</small></section><section class="card report-stat"><label>Power Consumption</label><strong>Efficient</strong><small>Low-power LoRa communication</small></section><section class="card report-stat"><label>Communication Range</label><strong>Long range</strong><small>Qualitative project capability</small></section></div><section class="card panel"><div class="section-heading"><h2>Telemetry Snapshot</h2><p>Current demo data</p></div><div class="chart-wrap" style="height:300px"><canvas id="reportChart"></canvas></div><div class="report-note">This report contains simulated interface data. The project documentation supports approximately 200 ms latency, reliable transmission, efficient power usage and stable long-distance communication; no exact packet delivery percentage or range is claimed here.</div></section>`;
  createChart('reportChart', { type: 'bar', data: { labels: ['Active soldiers', 'Online nodes', 'Active alerts', 'Avg. battery'], datasets: [{ data: [12, 18, 2, 82], backgroundColor: ['#1e5e87', '#6f9eb4', '#c54a4a', '#25815f'], borderRadius: 3, barThickness: 35 }] }, options: { ...chartOptions('Demo value'), scales: { x: { grid: { display: false }, ticks: { color: '#718091' } }, y: { beginAtZero: true, grid: { color: '#edf0f2' }, ticks: { color: '#718091' } } } } });
  document.getElementById('generateReport').addEventListener('click', () => window.print());
}

function openModal(content) { document.getElementById('modalContent').innerHTML = content; document.getElementById('modalBackdrop').classList.remove('hidden'); }
function closeModal() { document.getElementById('modalBackdrop').classList.add('hidden'); }
function setTimeText() { const target = document.getElementById('pageTime'); if (target) target.textContent = document.getElementById('topTime').textContent; }
function render(view) { currentView = view; chartInstances.forEach(chart => chart.destroy()); chartInstances = []; if (mapInstance) { mapInstance.remove(); mapInstance = null; } ({ dashboard: renderDashboard, soldiers: renderSoldiers, live: renderLive, sensors: renderSensors, alerts: renderAlerts, gas: renderGasDatabase, network: renderNetwork, reports: renderReports }[view] || renderDashboard)(); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); document.getElementById('breadcrumbCurrent').textContent = pageNames[view]; document.getElementById('sidebar').classList.remove('open'); document.getElementById('mobileScrim').classList.remove('open'); }
function updateClock() { const date = new Date('2026-09-13T09:45:00'); const elapsed = Math.floor((Date.now() - window.demoStart) / 1000); date.setSeconds(date.getSeconds() + elapsed); const formatted = date.toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }); document.getElementById('topTime').textContent = formatted; setTimeText(); }

document.addEventListener('click', event => { const nav = event.target.closest('[data-view]'); if (nav) render(nav.dataset.view); const viewAction = event.target.closest('[data-view-action]'); if (viewAction) render(viewAction.dataset.viewAction); const alertFilter = event.target.closest('[data-alert-filter]'); if (alertFilter) { render('alerts'); setTimeout(() => document.querySelector(`[data-filter="${alertFilter.dataset.alertFilter}"]`)?.click(), 0); } const soldierButton = event.target.closest('[data-soldier]'); if (soldierButton) showSoldier(soldierButton.dataset.soldier); const alertButton = event.target.closest('[data-alert]'); if (alertButton) showAlert(alertButton.dataset.alert); });
document.getElementById('menuToggle').addEventListener('click', () => { document.getElementById('sidebar').classList.add('open'); document.getElementById('mobileScrim').classList.add('open'); });
document.getElementById('sidebarClose').addEventListener('click', () => { document.getElementById('sidebar').classList.remove('open'); document.getElementById('mobileScrim').classList.remove('open'); });
document.getElementById('mobileScrim').addEventListener('click', () => { document.getElementById('sidebar').classList.remove('open'); document.getElementById('mobileScrim').classList.remove('open'); });
document.getElementById('modalClose').addEventListener('click', closeModal); document.getElementById('modalBackdrop').addEventListener('click', event => { if (event.target.id === 'modalBackdrop') closeModal(); });
window.demoStart = Date.now(); render('dashboard'); updateClock(); setInterval(updateClock, 1000);
